// Copyright 2021 Manna Harbour
// https://github.com/manna-harbour/miryoku
MIRYOKU_ALPHAS=QWERTY
MIRYOKU_TAP=QWERTY
MIRYOKU_EXTRA=QWERTY
MIRYOKU_NAV=DEFAULT
MIRYOKU_CLIPBOARD=WIN
MIRYOKU_LAYERS=DEFAULT
